spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.application.name=cinema-gestion
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
server.port=${SERVER_PORT}

security.jwt.secret=${JWT_SECRET}
security.jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
security.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}
#security.route.public.paths=${SECURITY_PUBLIC_PATHS:/auth/register,/auth/login,/auth/refresh}